spring:
  application:
    name: ${SPRING_APPLICATION_NAME:payment-system}

  # mysql setting
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mydb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:12345678}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

  # JPA/Hibernate setting
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

# PortOne API Configuration
portone:
  api:
    secret: ${PORTONE_API_SECRET:wyXJV0i3sypyon5uY8jKJL8HiPXzMJWfm4OvmSkHXnWZ3uVKZ9PtThLmFFwkuAb3y59VJAR1DrbLhtKA}
    url: ${PORTONE_API_URL:https://api.portone.io/}

  # KG inicis with portone
  store:
    id: ${PORTONE_STORE_ID:store-26aa9b80-8368-41c6-b05a-31b92973ec4e}

  channel:
    key: ${PORTONE_CHANNEL_KEY:channel-key-9625470d-85bd-425f-b68a-7978db63cff7}

  pg:
    mid: ${PORTONE_PG_MID:INIpayTest}

  web:
    signkey: ${PORTONE_WEB_SIGNKEY:SU5JTElURV9UUklQTEVERVNfS0VZU1RS}

  ini:
    api:
      key: ${PORTONE_INI_API_KEY:ItEQKi3rY7uvDS8l}
      iv: ${PORTONE_INI_API_IV:HYb3yQ4f65QL89==}

  webhook:
    secret: ${PORTONE_WEBHOOK_SECRET:https://smee.io/ayLYc1ZQ3fiJrfH}

# Jwt token secret
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
